Fix error building image
- __Error__

```
ERROR: unsatisfiable constraints:
    python (missing):
      required by: world[python]
```

- __Fix__

In docker file changed `python` to `python2`

Changed:

```Dockerfile
    apk add \
     	  ca-certificates \
    	  groff \
    	  less \
        curl \
    	  python \
    	  py-pip \
        unzip \
```

To:

```Dockerfile
    apk add \
     	  ca-certificates \
    	  groff \
    	  less \
        curl \
    	  python2 \
    	  py-pip \
        unzip \
```